---
- hosts: hadoop-cluster
  become: yes
  gather_facts: True
  vars:
    
# Machines hostnames   
    master1: hadoop3.cluster
    master2: hadoop4.cluster

# hadoop & zookeeper version
    hadoop_archive_url: https://archive.apache.org/dist/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz
    zookeeper_archive_url: https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz

# Important directories 


    working_dir: /svc
    

    hadoop_dir: /svc/app/hadoop
    zookeeper_dir: /svc/app/zookeeper


    namenode_Dir: /svc/data/nameNode

    datanode_Dir: /svc/data/dataNode



  roles:

     - config-hadoop
