- name: Create hadoop user accounts with "hadoop" password
  user:
    name: hadoop
    state: present
    password: $1$rYWXEZ03$96uSe23XrOf1XrNZB5PRK1

- name: Generate SSH key for hadoop user
  become_user: hadoop
  command: ssh-keygen -t rsa -f /home/hadoop/.ssh/id_rsa -N ''
  args:
    creates: /home/hadoop/.ssh/id_rsa


- name: create zookeeperdata working directory
  file:
    path: "{{ item }}"
    state: directory
    owner: hadoop
    group: hadoop
  with_items:
    - "{{ working_dir }}/app"
    - "{{ zookeeper_dir }}/zookeeperdata"
    - "{{ zookeeper_dir }}/zookeeper"
    - "{{ hadoop_dir }}/hadoop"

- name: Install JDK 8 
  yum:
    name: ['rsync', 'java-1.8.0-openjdk.x86_64']
    state: present

- name: install hadoop 2_7_3 & zookeeeper 3_4_6
  get_url:
    url: "{{ item }}" 
    dest: "{{ working_dir }}"
    owner: hadoop
    group: hadoop
  with_items:
    - "{{ hadoop_archive_url }}"
    - "{{ zookeeper_archive_url }}"

- name: Extract archive hadoop
  unarchive:
    src: "{{ working_dir }}/hadoop-2.7.3.tar.gz"
    dest: "{{ hadoop_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: hadoop
    group: hadoop

- name: Extract archive zookeeper
  unarchive:
    src: "{{ working_dir }}/zookeeper-3.4.6.tar.gz"
    dest: "{{ zookeeper_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: hadoop
    group: hadoop

- name: Set Env hadoop & java & zookeeper to bashrc
  blockinfile:
    path: /home/hadoop/.bashrc
    block: |
      export HADOOP_HOME=/svc/app/hadoop
      export ZOOKEEPER_HOME=/svc/app/zookeeper
      export PATH=${PATH}:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin
      export PATH=${PATH}:$ZOOKEEPER_HOME/bin
      export PATH=${PATH}:$JAVA_HOME/bin
      export PATH=/svc/app/hadoop/bin:/svc/app/hadoop/sbin:$PATH
      export PATH=/svc/app/zookeeper/bin:/svc/app/appzookeeper/bin:$PATH

- name: create zookeeper working directory
  file:
    path: "{{ zookeeper_dir }}/zookeeperdata/myid"
    state: touch
    owner: hadoop
    group: hadoop

- name: add java home path 
  replace:
    path: /svc/app/hadoop/etc/hadoop/hadoop-env.sh
    regexp: '^export JAVA_HOME=\${JAVA_HOME}'
    replace: "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre"

- name: add hadoop conf files 
  template:
    src: "{{ item }}.j2"
    dest: "{{ hadoop_dir }}/etc/hadoop/{{ item }}"
    owner: hadoop
    group: hadoop
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - slaves

- name: add hadoop conf files
  template:
    src: "{{ item }}.j2"
    dest: "{{ zookeeper_dir }}/conf/{{ item }}"
    owner: hadoop
    group: hadoop
  with_items:
    - "zoo.cfg"

- name: delete zookeeper.gz hadoop.gz
  file:
    path: "{{ working_dir }}/{{ item }}"
    state: absent
  with_items:
    - hadoop-2.7.3.tar.gz
    - zookeeper-3.4.6.tar.gz

- name: CHANGE THE HOSTNAME for MASTER hadoop Conf original is test1
  replace:
    path: "{{ item }}"
    regexp: '\b(\w*test1\w*)\b'
    replace: "{{ master1 }}"
  with_items:
    - "{{ hadoop_dir }}/etc/hadoop/core-site.xml"
    - "{{ hadoop_dir }}/etc/hadoop/hdfs-site.xml"
    - "{{ hadoop_dir }}/etc/hadoop/slaves"
    - "{{ zookeeper_dir }}/conf/zoo.cfg"

- name: CHANGE THE HOSTNAME for STANDBY hadoop Conf original is test2
  replace:
    path: "{{ item }}"
    regexp: '\b(\w*test2\w*)\b'
    replace: "{{ master2 }}"
  with_items:
    - "{{ hadoop_dir }}/etc/hadoop/core-site.xml"
    - "{{ hadoop_dir }}/etc/hadoop/hdfs-site.xml"
    - "{{ hadoop_dir }}/etc/hadoop/slaves"
    - "{{ zookeeper_dir }}/conf/zoo.cfg"

- name: Set NameNode directory
  replace:
    path: "{{ item }}"
    regexp: '\/home\/hadoop\/data\/nameNode'
    replace: "{{ namenode_Dir }}"
  with_items:
    - "{{ hadoop_dir }}/etc/hadoop/hdfs-site.xml"

- name: Set DameNode directory
  replace:
    path: "{{ item }}"
    regexp: '\/home\/hadoop\/data\/dataNode'
    replace: "{{ datanode_Dir }}"
  with_items:
    - "{{ hadoop_dir }}/etc/hadoop/hdfs-site.xml"











