{
 "title": "HDFS Services Status",
 "description": "Hadoop HA Services Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NameNode-Master",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "hadoop_hadoop_namenode_process_up{instance=\"192.168.55.78:9108\",job=\"prometheus\"}",
     "legendFormat": "NameNode-Master"
    }
   ]
  },
  {
   "title": "DataNode-Master",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "hadoop_hadoop_datanode_process_up{instance=\"192.168.55.78:9108\",job=\"prometheus\"}",
     "legendFormat": "DataNode-Master"
    }
   ]
  },
  {
   "title": "JournalNode-Master",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "hadoop_hadoop_journalnode_process_up{instance=\"192.168.55.78:9108\",job=\"prometheus\"}",
     "legendFormat": "JournalNode-Master"
    }
   ]
  },
  {
   "title": "ZKFC-Master",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "hadoop_hadoop_zkfc_process_up{instance=\"192.168.55.78:9108\",job=\"prometheus\"}",
     "legendFormat": "ZKFC-Master"
    }
   ]
  },
  {
   "title": "Zookeeper-Master",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "zookeeper_server_process_up{instance=\"192.168.55.78:9108\",job=\"prometheus\"}",
     "legendFormat": "Zookeeper-Master"
    }
   ]
  },
  {
   "title": "NameNode-Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "hadoop_hadoop_namenode_process_up{instance=\"192.168.55.79:9109\",job=\"prometheus\"}",
     "legendFormat": "NameNode-Standby"
    }
   ]
  },
  {
   "title": "DataNode-Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "hadoop_hadoop_datanode_process_up{instance=\"192.168.55.79:9109\",job=\"prometheus\"}",
     "legendFormat": "DataNode-Standby"
    }
   ]
  },
  {
   "title": "JournalNode-Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "hadoop_hadoop_journalnode_process_up{instance=\"192.168.55.79:9109\",job=\"prometheus\"}",
     "legendFormat": "JournalNode-Standby"
    }
   ]
  },
  {
   "title": "ZKFC-Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "targets": [
    {
     "expr": "hadoop_hadoop_zkfc_process_up{instance=\"192.168.55.79:9109\",job=\"prometheus\"}",
     "legendFormat": "ZKFC-Standby"
    }
   ]
  },
  {
   "title": "Zookeeper-Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "zookeeper_server_process_up{instance=\"192.168.55.79:9109\",job=\"prometheus\"}",
     "legendFormat": "Zookeeper-Standby"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hadoop_datanode_process_up{instance=\"192.168.55.79:9109\",job=\"prometheus\"}"
    }
   ]
  }
 ]
}